trigger:
  branches:
    include:
    - master
    - integration
    - sp-1.6.0

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release

steps:
- task: UseDotNet@2
  displayName: Install .NET 10 SDK
  inputs:
    packageType: sdk
    version: 10.0.x

- task: MicrosoftSecurityDevOps@1
  displayName: Run Microsoft Security DevOps

- powershell: dotnet restore .\SuperPutty.sln
  displayName: Restore solution

- powershell: dotnet build .\SuperPutty.sln -c $(buildConfiguration) --no-restore
  displayName: Build application and installer

- powershell: dotnet test .\SuperPuttyUnitTests\SuperPuttyUnitTests.csproj -c $(buildConfiguration) --no-build --filter "TestCategory!~Net"
  displayName: Run automated tests

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.SourcesDirectory)\SuperPuttyInstaller\bin\$(buildConfiguration)\SuperPuttySetup.msi
    artifactType: pipeline
    artifactName: SuperPutty-1.6.0-win-x64
